version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: ${DB_HOST}        
      DB_PORT: ${DB_PORT}        
      DB_USERNAME: ${DB_USERNAME} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_DATABASE: ${DB_DATABASE} 
      THROTTLE_TTL: ${THROTTLE_TTL} 
      THROTTLE_LIMIT: ${THROTTLE_LIMIT} 
    depends_on:
      - db

  db:
    image: postgres:15  
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_DATABASE} 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: